import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./prime.scss";

import Nav from "./app-header/nav";
import Toast from "./app-header/toast";
import { Toaster } from "@/components/auth/Toasts/toaster";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                {children}
                <Toast />
                <Suspense>
                    <Toaster />
                </Suspense>
            </body>
        </html>
    );
}
